name: Python 3.11 Build Test

on:
  schedule:
    - cron: "0 10 */7 * *" # weekly

jobs:
  build:
    # https://github.com/actions/setup-python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11-dev"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run unittest
        run: |
          python -m unittest discover "tests" -p '*_test.py'
