name: Build release packages

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build-windows:
    name: Build Windows MSI
    runs-on: windows-latest
    outputs:
      release_url: ${{ steps.release.outputs.url }}
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Build package
        run: |
          uv run --group build scripts/setup_msi.py bdist_msi --target-version ${{github.ref_name}}
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: './dist/pyclashbot*.msi'
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          prerelease: ${{startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')}}
          generate_release_notes: true
          files: |
            ./dist/pyclashbot*.msi

  build-macos:
    name: Build macOS DMG
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Build package
        run: |
          uv run --group build scripts/setup_macos.py --target-version ${{github.ref_name}}
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: './dist/py-clash-bot*.dmg'
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')}}
          files: |
            ./dist/py-clash-bot*.dmg

  notify:
    name: Send Discord notification
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Trigger Discord Webhook
        run: |
          uv run --group build scripts/trigger_discord_webhook.py \
            --version "${{ github.ref_name }}" \
            --url "${{ needs.build-windows.outputs.release_url }}" \
            --webhook-code "${{ secrets.DISCORD_WEBHOOK_CODE }}" \
            ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc') && '--prerelease' || '' }}
